"""
Django settings for clinicaConfig project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r-)7z)mrp%!86qwjv9o_yvl1(_dkv#575xtc)6t+yvq$cv7u9r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = [
#     "127.0.0.1",
#     "localhost",
#     "10.0.0.114"
# ]

ALLOWED_HOSTS = ["*"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Django rest framework
    'rest_framework',
    # django rest framework para autenticação
    # 'rest_framework_simplejwt', TIREIO PORQUE ESTAVA DANDO ERRO O CORRETO É SÓ rest_framework

    #para documentar a api
    'drf_yasg',

    # o corsheaders permite a comunicação com domínios diferentes
    'corsheaders',

    'clinicaEstetica',
    #'administrador',
    'administrador.apps.AdministradorConfig',
    #'cliente',
    'cliente.apps.ClienteConfig',
    # 'profissional',
    'profissional.apps.ProfissionalConfig', # diz ao django qual app de configuração ele deve fazer a inicialiazação
    'servico',
    'plano',
    'usuarioAutenticacao'
]

# configurações da autenticação JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':(
        # informa que a API está usando JWT para autenticação, que é responsável por gerar e válidar tokéns
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES':(
        # define que todas as rotas da API só seja acessada por usuários autenticados
        'rest_framework.permissions.IsAuthenticated',
    )
}

# Tempo de expiração do tokén
SIMPLE_JWT = {
    # tempo de expiração do tokén de acesso
    "ACCES_TOKEN_LIFETIME": timedelta(minutes=60),
    # tempo de expiração do tokén de refresh
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # torna inválido o refresh antigo
    "BLACKLIST_AFTER_ROTATION": True,
}

MIDDLEWARE = [
    # MIDDLEWAREs relacionados ao corsheaders
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clinicaConfig.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ #BASE_DIR / 'clinicaEstetica',
        #          BASE_DIR / 'administrador/templates',
        #          BASE_DIR / 'cliente/templates',
        #          BASE_DIR / 'servico/templates',
                   BASE_DIR / 'templates',
                   BASE_DIR / 'cliente' / 'templates',
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clinicaConfig.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# cros origin
# aceita requisições de todos os dominios
# CORS_ALLOWED_ORIGINS = [
#     "http://127.0.0.1:8000",
#     "http://10.0.0.114:8000",
# ]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# habilita o envio de cookies entre backend e frontend
CORS_ALLOW_CREDENTIALS = True



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Configuração de Sessões: armazena os login
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'  # Usa a memória cache para gerenciar as sessões
#SESSION_COOKIE_AGE = 3600  # Tempo de expiração da sessão (1 hora)
#SESSION_SAVE_EVERY_REQUEST = False  # Não salva a sessão em cada requisição
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expira a sessão ao fechar o navegador
SESSION_COOKIE_SECURE = True  # Garante que a sessão seja transmitida apenas via HTTPS


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_DIRS = [
    os.path.join(BASE_DIR, 'clinicaEstetica/static'),
    os.path.join(BASE_DIR, 'administrador/static'),
    os.path.join(BASE_DIR, 'cliente/static'),
    os.path.join(BASE_DIR, 'plano/static'),
    os.path.join(BASE_DIR, 'profissional/static'),
]
MEDIA_ROOT = os.path.join(BASE_DIR, 'Media')
MEDIA_URL = '/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/clinicaEstetica/index'
LOGIN_REDIRECT_URL = '/administrador/indexAdm'
LOGIN_REDIRECT_URL = '/cliente/index'
LOGIN_REDIRECT_URL = '/profissional/verProfissional'
LOGIN_REDIRECT_URL = '/servico/index'
LOGIN_REDIRECT_URL = '/accounts/login/'
