# Generated by Django 5.2.8 on 2025-12-05 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('endereco', models.CharField(max_length=150)),
                ('especializacao', models.CharField(max_length=100)),
                ('numTelefone', models.IntegerField()),
                ('salario', models.IntegerField()),
                ('identificador', models.CharField(default='profissional', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('detail_profissional', 'Pode ver detalhe do profissional '),),
            },
        ),
    ]
