# Generated by Django 5.2.8 on 2025-12-05 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendarServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('horario', models.TimeField()),
                ('servico', models.ManyToManyField(null=True, to='servico.servico')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=100)),
                ('telefone', models.IntegerField(blank=True, max_length=20)),
                ('identificador', models.CharField(default='cliente', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('detail_cliente', 'Pode ver detalhe do perfil'), ('AgendarServico_cliente', 'Pode agendar um servico')),
            },
        ),
    ]
