# Generated by Django 5.2.8 on 2025-12-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='statusServico',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartão', 'Cartão')], default='dinheiro', max_length=20),
        ),
    ]
