# Generated by Django 5.2.8 on 2025-12-10 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_delete_agendarservico'),
        ('servico', '0003_remove_agendamento_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartão')], default='dinheiro', max_length=20),
        ),
    ]
